config/routes.rb
Group3SugarCycles::Application.routes.draw do
  resources :orders

  resources :bikes

  resources :types

  resources :customers

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.desc %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @type.desc %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>